version: "3.3"
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs-starter
    ports:
      - "5432:5432"
